.catalog:
  name: "RocketChat"
  version: "v0.2"
  description: "Have your own Slack like online chat, built with Meteor."
  uuid: rocketchat-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "MONGO_DB_PATH"
    - variable: "ROCKET_UPLOAD_PATH"
rocketchat:
  scale: 1
db:
  scale: 1
